title: Oxide
description: Oxide is an abstracted, modular, and extensible mod and plugin framework for any game that uses .NET
baseurl: ""
url: "/"
github_username:  OxideMod

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - .vscode/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
